import fs from "node:fs";
import path from "node:path";
import { parse } from "yaml";
import type { Plugin } from "vite";

const ROOT = process.cwd();
const PROJECTS_DIR = path.join(ROOT, "projects");
const OUT_DIR = path.join(ROOT, "src/lib/projects");
const OUT_FILE = path.join(OUT_DIR, "index.ts");

const BASE_LOCALE = "en";
const LOCALES = ["en", "de"];

interface EnProjectEntry {
  id: string;
  title: string;
  description: string;
  link: string;
  tags?: string[];
}

interface LocalizedProjectEntry {
  id: string;
  title: string;
  description: string;
}

function readYaml<T>(file: string): T {
  return parse(fs.readFileSync(file, "utf-8")) as T;
}

function generate() {
  const en = readYaml<{ tags?: string[]; projects: EnProjectEntry[] }>(
    path.join(PROJECTS_DIR, `${BASE_LOCALE}.yaml`),
  );
  const enProjects = en.projects ?? [];
  const enIds = new Set(enProjects.map((p) => p.id));

  const usedOther = enProjects.some((p) => !p.tags || p.tags.length === 0);
  const tags = [...(en.tags ?? []), ...(usedOther ? ["other"] : [])];

  const projectsByLocale: Record<string, EnProjectEntry[]> = {
    [BASE_LOCALE]: enProjects.map((p) => ({ ...p, tags: p.tags?.length ? p.tags : ["other"] })),
  };

  for (const locale of LOCALES) {
    if (locale === BASE_LOCALE) continue;

    const localeFile = path.join(PROJECTS_DIR, `${locale}.yaml`);
    const localeData = readYaml<{ projects?: LocalizedProjectEntry[] }>(localeFile);
    const overrides = localeData.projects ?? [];

    for (const override of overrides) {
      if (!enIds.has(override.id)) {
        throw new Error(
          `[generate-projects] ${locale}.yaml references unknown project id "${override.id}" ` +
            `(not present in ${BASE_LOCALE}.yaml)`,
        );
      }
    }

    const overrideMap = new Map(overrides.map((p) => [p.id, p]));

    projectsByLocale[locale] = enProjects.map((p) => {
      const override = overrideMap.get(p.id);
      return {
        id: p.id,
        title: override?.title ?? p.title,
        description: override?.description ?? p.description,
        link: p.link,
        tags: p.tags?.length ? p.tags : ["other"],
      };
    });
  }

  const output = `// Auto-generated by vite-plugins/generate-projects.ts from projects/*.yaml — do not edit.
export interface Project {
  id: string;
  title: string;
  description: string;
  link: string;
  tags: string[];
}

export type Locale = "${LOCALES.join('" | "')}";

export const tags: string[] = ${JSON.stringify(tags, null, 2)} satisfies string[];

export const projectsByLocale: Record<Locale, Project[]> = ${JSON.stringify(projectsByLocale, null, 2)} satisfies Record<Locale, Project[]>;
`;

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(OUT_FILE, output);
  fs.writeFileSync(path.join(OUT_DIR, ".gitignore"), "*\n");

  console.log(`[generate-projects] generated ${enProjects.length} projects for ${LOCALES.length} locales`);
}

export function generateProjectsPlugin(): Plugin {
  return {
    name: "generate-projects",
    buildStart() {
      generate();
      for (const locale of LOCALES) {
        this.addWatchFile(path.join(PROJECTS_DIR, `${locale}.yaml`));
      }
    },
    handleHotUpdate(ctx) {
      // because we cannt be sure of the path-system, we must use path to normalize the paths before comparing them
      const normalizedFile = path.normalize(ctx.file);
      const normalizedProjectsDir = path.normalize(PROJECTS_DIR);
      if (!normalizedFile.startsWith(normalizedProjectsDir)) return;

      console.log(`[generate-projects] regenerating projects...`);
      generate();

      const mods = ctx.server.moduleGraph.getModulesByFile(OUT_FILE);
      if (!mods) return [];
      for (const mod of mods) ctx.server.moduleGraph.invalidateModule(mod);
      return [...mods, ...ctx.modules];
    },
  };
}
